FROM ngalayko/bazel-action:0.29.0

LABEL name="Bazel Action"
LABEL maintainer="Nikita Galaiko"
LABEL version="0.29.0"
LABEL repository="https://github.com/ngalaiko/bazel-action"

LABEL com.github.actions.name="Bazel Action"
LABEL com.github.actions.description="Run Bazel commands"
LABEL com.github.actions.icon="box"
LABEL com.github.actions.color="green"
